//功能： 将青果记账的数据批量导入多多记账
// 本代码仅在已登录微信的页面生效，可借助qq浏览器微信登录插件登录微信
// 登录后打开多多记账，进入自己的账单页面，然后即可执行以下代码快速批
// 量导入自己的账单;

/******自己的数据*******/
//待导入的数据
var data = {
  "2016-06-01": [
    {
      "id": 817936,
      "owner": 2,
      "currency": 8,
      "currency_type": 1,
      "type": 0,
      "category": 2,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "8坐地铁",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-01"
    },
    {
      "id": 817935,
      "owner": 2,
      "currency": 17,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "吃饭十七元！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-01"
    },
    {
      "id": 817932,
      "owner": 2,
      "currency": 12,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "吃饭十二！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-01"
    }
  ],
  "2016-06-02": [
    {
      "id": 818391,
      "owner": 2,
      "currency": 2,
      "currency_type": 1,
      "type": 0,
      "category": 2,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "坐公交两块！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-02"
    },
    {
      "id": 818388,
      "owner": 2,
      "currency": 2,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买口香糖两块！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-02"
    },
    {
      "id": 818094,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐三块钱！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-02"
    },
    {
      "id": 818077,
      "owner": 2,
      "currency": 50,
      "currency_type": 1,
      "type": 0,
      "category": 6,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "充话费五十！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-02"
    },
    {
      "id": 818008,
      "owner": 2,
      "currency": 6049,
      "currency_type": 1,
      "type": 1,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "这个月的工资六千零四十九！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-02"
    },
    {
      "id": 818006,
      "owner": 2,
      "currency": 3.3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早晨买包子什么三块三！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-02"
    },
    {
      "id": 818484,
      "owner": 2,
      "currency": 2,
      "currency_type": 1,
      "type": 0,
      "category": 2,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "坐公交两块钱！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-02"
    }
  ],
  "2016-06-03": [
    {
      "id": 819174,
      "owner": 2,
      "currency": 50,
      "currency_type": 1,
      "type": 0,
      "category": 6,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "丫头给我充了五十块钱的话费！我给他打过去了！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-03"
    },
    {
      "id": 819122,
      "owner": 2,
      "currency": 2,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买包子两块钱！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-03"
    },
    {
      "id": 819097,
      "owner": 2,
      "currency": 0,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "今天跟老板提离职了零块钱！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-03"
    },
    {
      "id": 818697,
      "owner": 2,
      "currency": 3.3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买包子三块三！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-03"
    },
    {
      "id": 819176,
      "owner": 2,
      "currency": 13.5,
      "currency_type": 1,
      "type": 0,
      "category": 6,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "小米电话加油包！充值十三块五！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-03"
    }
  ],
  "2016-06-04": [
    {
      "id": 819762,
      "owner": 2,
      "currency": 10,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "昨天吃晚饭十块钱！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-04"
    },
    {
      "id": 819712,
      "owner": 2,
      "currency": 0,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "今天帮胖胖搬家零块钱！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-04"
    },
    {
      "id": 819411,
      "owner": 2,
      "currency": 4.5,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐四块五！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-04"
    },
    {
      "id": 819700,
      "owner": 2,
      "currency": 12,
      "currency_type": 1,
      "type": 0,
      "category": 2,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "帮胖胖搬家坐地铁，公交十二块钱！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-04"
    }
  ],
  "2016-06-05": [
    {
      "id": 820399,
      "owner": 2,
      "currency": 13,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐13块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-05"
    }
  ],
  "2016-06-06": [
    {
      "id": 821001,
      "owner": 2,
      "currency": 4950,
      "currency_type": 1,
      "type": 0,
      "category": 6,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "交房租四千九百五！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-06"
    },
    {
      "id": 821000,
      "owner": 2,
      "currency": 11,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买菜十一块钱！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-06"
    },
    {
      "id": 820645,
      "owner": 2,
      "currency": 15,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐15块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-06"
    }
  ],
  "2016-06-07": [
    {
      "id": 821439,
      "owner": 2,
      "currency": 128.5,
      "currency_type": 1,
      "type": 0,
      "category": 2,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买火车票一百二十八块五！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-07"
    },
    {
      "id": 821191,
      "owner": 2,
      "currency": 3.3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买包子3块3",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-07"
    }
  ],
  "2016-06-08": [
    {
      "id": 822091,
      "owner": 2,
      "currency": 16,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "做么低十六！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-08"
    },
    {
      "id": 821864,
      "owner": 2,
      "currency": 0,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "端午节回去看丫头0元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-08"
    },
    {
      "id": 821861,
      "owner": 2,
      "currency": 13,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐13",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-08"
    },
    {
      "id": 821860,
      "owner": 2,
      "currency": 3.3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买包子33",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-08"
    },
    {
      "id": 821862,
      "owner": 2,
      "currency": 19.5,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "坐火车前采购食品195",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-08"
    },
    {
      "id": 823548,
      "owner": 2,
      "currency": 16,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "做摩的16",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-08"
    },
    {
      "id": 823549,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 2,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "坐地铁4元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-08"
    }
  ],
  "2016-06-09": [
    {
      "id": 822602,
      "owner": 2,
      "currency": 130.2,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "大润发购物1302",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-09"
    },
    {
      "id": 822601,
      "owner": 2,
      "currency": 13,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐13",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-09"
    },
    {
      "id": 822603,
      "owner": 2,
      "currency": 1,
      "currency_type": 1,
      "type": 0,
      "category": 3,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "大润发购物1元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-09"
    }
  ],
  "2016-06-10": [
    {
      "id": 823535,
      "owner": 2,
      "currency": 10,
      "currency_type": 1,
      "type": 0,
      "category": 2,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "打的10块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-10"
    },
    {
      "id": 823536,
      "owner": 2,
      "currency": 79,
      "currency_type": 1,
      "type": 0,
      "category": 3,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买鞋79",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-10"
    },
    {
      "id": 823537,
      "owner": 2,
      "currency": 97,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "吃牛排97",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-10"
    },
    {
      "id": 823542,
      "owner": 2,
      "currency": 56,
      "currency_type": 1,
      "type": 0,
      "category": 3,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "逛超市56",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-10"
    }
  ],
  "2016-06-11": [
    {
      "id": 823546,
      "owner": 2,
      "currency": 32,
      "currency_type": 1,
      "type": 0,
      "category": 3,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "逛超市32",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-11"
    }
  ],
  "2016-06-12": [
    {
      "id": 823671,
      "owner": 2,
      "currency": 25,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买了一把伞！二十五！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-12"
    },
    {
      "id": 823670,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 2,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "坐地铁四块钱！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-12"
    },
    {
      "id": 823669,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐四块钱！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-12"
    },
    {
      "id": 824587,
      "owner": 2,
      "currency": 12,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午饭十二！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-12"
    },
    {
      "id": 824591,
      "owner": 2,
      "currency": 5.9,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买菜五块九！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-12"
    },
    {
      "id": 824593,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买馒头三块！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-12"
    }
  ],
  "2016-06-13": [
    {
      "id": 824594,
      "owner": 2,
      "currency": 3.3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐三块三！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-13"
    },
    {
      "id": 824588,
      "owner": 2,
      "currency": 12,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午饭十二！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-13"
    }
  ],
  "2016-06-14": [
    {
      "id": 825147,
      "owner": 2,
      "currency": 128.5,
      "currency_type": 1,
      "type": 0,
      "category": 2,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "购买7月1日火车票！一百二十八块五！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-14"
    },
    {
      "id": 825140,
      "owner": 2,
      "currency": 3.3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐三块三！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-14"
    }
  ],
  "2016-06-15": [
    {
      "id": 825619,
      "owner": 2,
      "currency": 3.3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐33",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-15"
    },
    {
      "id": 825664,
      "owner": 2,
      "currency": 17,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐十‘七块！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-15"
    }
  ],
  "2016-06-16": [
    {
      "id": 826030,
      "owner": 2,
      "currency": 3.3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐33",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-16"
    },
    {
      "id": 826029,
      "owner": 2,
      "currency": 10,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午饭10元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-16"
    }
  ],
  "2016-06-17": [
    {
      "id": 826445,
      "owner": 2,
      "currency": 10,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午饭10元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-17"
    },
    {
      "id": 826654,
      "owner": 2,
      "currency": 10,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买菜十块钱！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-17"
    }
  ],
  "2016-06-18": [
    {
      "id": 827200,
      "owner": 2,
      "currency": 13.5,
      "currency_type": 1,
      "type": 0,
      "category": 6,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "充话费十三块五！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-18"
    }
  ],
  "2016-06-19": [
    {
      "id": 827912,
      "owner": 2,
      "currency": 19,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "昨天吃饭十九块！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-19"
    }
  ],
  "2016-06-20": [
    {
      "id": 828219,
      "owner": 2,
      "currency": 9,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚饭九块钱！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-20"
    },
    {
      "id": 828218,
      "owner": 2,
      "currency": 13,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午饭十三！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-20"
    }
  ],
  "2016-06-21": [
    {
      "id": 828539,
      "owner": 2,
      "currency": 6.32,
      "currency_type": 1,
      "type": 0,
      "category": 3,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买偶尔遇见的传奇电子书632",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-21"
    },
    {
      "id": 828538,
      "owner": 2,
      "currency": 13,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午饭13",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-21"
    }
  ],
  "2016-06-22": [
    {
      "id": 829153,
      "owner": 2,
      "currency": 25,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买菜二十五！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-22"
    },
    {
      "id": 829151,
      "owner": 2,
      "currency": 10,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午饭十块钱！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-22"
    },
    {
      "id": 829150,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午饭吃三块钱！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-22"
    },
    {
      "id": 829155,
      "owner": 2,
      "currency": 5,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买生煎五块钱！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-22"
    },
    {
      "id": 829156,
      "owner": 2,
      "currency": 140,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "体检一百次！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-22"
    }
  ],
  "2016-06-23": [
    {
      "id": 829335,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐3块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-23"
    },
    {
      "id": 829824,
      "owner": 2,
      "currency": 33,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐三十三！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-23"
    },
    {
      "id": 829825,
      "owner": 2,
      "currency": 0,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐零元！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-23"
    },
    {
      "id": 830874,
      "owner": 2,
      "currency": 8,
      "currency_type": 1,
      "type": 0,
      "category": 2,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "地铁8块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-23"
    }
  ],
  "2016-06-24": [
    {
      "id": 829823,
      "owner": 2,
      "currency": 8,
      "currency_type": 1,
      "type": 0,
      "category": 2,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "地铁八块钱！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-24"
    },
    {
      "id": 830867,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐3块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-24"
    },
    {
      "id": 830868,
      "owner": 2,
      "currency": 17,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐17",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-24"
    },
    {
      "id": 830869,
      "owner": 2,
      "currency": 6,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐6块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-24"
    }
  ],
  "2016-06-26": [
    {
      "id": 830870,
      "owner": 2,
      "currency": 18,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐18元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-26"
    }
  ],
  "2016-06-27": [
    {
      "id": 831565,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐三！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-27"
    },
    {
      "id": 831563,
      "owner": 2,
      "currency": 8,
      "currency_type": 1,
      "type": 0,
      "category": 2,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "地铁八块钱！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-27"
    },
    {
      "id": 832210,
      "owner": 2,
      "currency": 30,
      "currency_type": 1,
      "type": 0,
      "category": 2,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "冲交通卡30",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-27"
    },
    {
      "id": 832211,
      "owner": 2,
      "currency": 21.5,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐报销215元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-27"
    }
  ],
  "2016-06-28": [
    {
      "id": 831782,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐三元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-28"
    },
    {
      "id": 832217,
      "owner": 2,
      "currency": 34,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买菜34元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-28"
    }
  ],
  "2016-06-29": [
    {
      "id": 832218,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐3元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-29"
    },
    {
      "id": 832835,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买馒头4块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-29"
    }
  ],
  "2016-06-30": [
    {
      "id": 832836,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐3块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-06-30"
    }
  ],
  "2016-07-01": [
    {
      "id": 833518,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐三块！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-01"
    },
    {
      "id": 833519,
      "owner": 2,
      "currency": 41,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐四十一！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-01"
    },
    {
      "id": 833520,
      "owner": 2,
      "currency": 9.4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-01"
    },
    {
      "id": 833521,
      "owner": 2,
      "currency": 14,
      "currency_type": 1,
      "type": 0,
      "category": 2,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "打车十四！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-01"
    }
  ],
  "2016-07-02": [
    {
      "id": 834224,
      "owner": 2,
      "currency": 42,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "吃牛排四十二！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-02"
    },
    {
      "id": 834225,
      "owner": 2,
      "currency": 30,
      "currency_type": 1,
      "type": 0,
      "category": 6,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "充话费三十！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-02"
    },
    {
      "id": 834226,
      "owner": 2,
      "currency": 59,
      "currency_type": 1,
      "type": 0,
      "category": 3,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买衣服五十九！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-02"
    }
  ],
  "2016-07-03": [
    {
      "id": 835072,
      "owner": 2,
      "currency": 10,
      "currency_type": 1,
      "type": 0,
      "category": 2,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "打车十块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-03"
    },
    {
      "id": 835033,
      "owner": 2,
      "currency": 9,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐9块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-03"
    }
  ],
  "2016-07-04": [
    {
      "id": 835035,
      "owner": 2,
      "currency": 11.8,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐118",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-04"
    },
    {
      "id": 835034,
      "owner": 2,
      "currency": 5.3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐53",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-04"
    }
  ],
  "2016-07-05": [
    {
      "id": 835470,
      "owner": 2,
      "currency": 50,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "交通五十！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-05"
    },
    {
      "id": 835469,
      "owner": 2,
      "currency": 13.5,
      "currency_type": 1,
      "type": 0,
      "category": 6,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "中话费十三块五！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-05"
    },
    {
      "id": 835468,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐三块！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-05"
    },
    {
      "id": 835471,
      "owner": 2,
      "currency": 24.5,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐二十四块五！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-05"
    },
    {
      "id": 835472,
      "owner": 2,
      "currency": 11,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐十一块！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-05"
    }
  ],
  "2016-07-06": [
    {
      "id": 836150,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐3元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-06"
    },
    {
      "id": 836152,
      "owner": 2,
      "currency": 6.5,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐65元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-06"
    },
    {
      "id": 836154,
      "owner": 2,
      "currency": 11.5,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐115",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-06"
    }
  ],
  "2016-07-07": [
    {
      "id": 836151,
      "owner": 2,
      "currency": 8,
      "currency_type": 1,
      "type": 0,
      "category": 2,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "地铁8元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-07"
    },
    {
      "id": 836149,
      "owner": 2,
      "currency": 11.8,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐118",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-07"
    },
    {
      "id": 836153,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐3块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-07"
    }
  ],
  "2016-07-08": [
    {
      "id": 836559,
      "owner": 2,
      "currency": 13.8,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐138",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-08"
    },
    {
      "id": 836458,
      "owner": 2,
      "currency": 800,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "借给张丁800块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-08"
    },
    {
      "id": 836455,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐3块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-08"
    },
    {
      "id": 837344,
      "owner": 2,
      "currency": 22,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐22",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-08"
    },
    {
      "id": 837345,
      "owner": 2,
      "currency": 0,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚上公司聚会ktv0元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-08"
    },
    {
      "id": 837346,
      "owner": 2,
      "currency": 8.3,
      "currency_type": 1,
      "type": 0,
      "category": 2,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚上打车83",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-08"
    }
  ],
  "2016-07-09": [
    {
      "id": 837347,
      "owner": 2,
      "currency": 10,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐10元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-09"
    },
    {
      "id": 837348,
      "owner": 2,
      "currency": 13,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐13",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-09"
    }
  ],
  "2016-07-11": [
    {
      "id": 838543,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐3块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-11"
    },
    {
      "id": 838545,
      "owner": 2,
      "currency": 18,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐17",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-11"
    }
  ],
  "2016-07-12": [
    {
      "id": 838546,
      "owner": 2,
      "currency": 11.8,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐118",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-12"
    },
    {
      "id": 838544,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐3块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-12"
    }
  ],
  "2016-07-13": [
    {
      "id": 838760,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐三块！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-13"
    },
    {
      "id": 838759,
      "owner": 2,
      "currency": 4.4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "帮别人买早餐四块四！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-13"
    },
    {
      "id": 838758,
      "owner": 2,
      "currency": 5,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "给胖子五块！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-13"
    },
    {
      "id": 838755,
      "owner": 2,
      "currency": 18.5,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐十八块五！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-13"
    }
  ],
  "2016-07-14": [
    {
      "id": 840598,
      "owner": 2,
      "currency": 50,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "充交通卡50",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-14"
    },
    {
      "id": 840606,
      "owner": 2,
      "currency": 12.8,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐罗森快餐128",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-14"
    },
    {
      "id": 840607,
      "owner": 2,
      "currency": 14,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐麻辣香锅14",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-14"
    },
    {
      "id": 840608,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐3元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-14"
    }
  ],
  "2016-07-15": [
    {
      "id": 840597,
      "owner": 2,
      "currency": 30,
      "currency_type": 1,
      "type": 0,
      "category": 6,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "充话费30",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-15"
    },
    {
      "id": 840602,
      "owner": 2,
      "currency": 12.5,
      "currency_type": 1,
      "type": 0,
      "category": 2,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "给丫头买巩义到郑州的火车票125",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-15"
    },
    {
      "id": 840603,
      "owner": 2,
      "currency": 11.8,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐118",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-15"
    },
    {
      "id": 840604,
      "owner": 2,
      "currency": 2,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐2块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-15"
    },
    {
      "id": 840605,
      "owner": 2,
      "currency": 15,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐15元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-15"
    }
  ],
  "2016-07-16": [
    {
      "id": 840596,
      "owner": 2,
      "currency": 13.5,
      "currency_type": 1,
      "type": 0,
      "category": 6,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "充话费135",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-16"
    },
    {
      "id": 840599,
      "owner": 2,
      "currency": 2.5,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "租赁百度会员25",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-16"
    },
    {
      "id": 840600,
      "owner": 2,
      "currency": 10,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐10元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-16"
    }
  ],
  "2016-07-17": [
    {
      "id": 841150,
      "owner": 2,
      "currency": 14,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐14",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-17"
    },
    {
      "id": 841152,
      "owner": 2,
      "currency": 66,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐66",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-17"
    }
  ],
  "2016-07-18": [
    {
      "id": 841153,
      "owner": 2,
      "currency": 14,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐14",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-18"
    },
    {
      "id": 841151,
      "owner": 2,
      "currency": 5,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐5块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-18"
    },
    {
      "id": 841955,
      "owner": 2,
      "currency": 7.8,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐七块吧！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-18"
    }
  ],
  "2016-07-19": [
    {
      "id": 841958,
      "owner": 2,
      "currency": 25,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐二十五！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-19"
    },
    {
      "id": 841957,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐三块！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-19"
    },
    {
      "id": 841956,
      "owner": 2,
      "currency": 7.8,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐七块八毛！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-19"
    }
  ],
  "2016-07-20": [
    {
      "id": 842505,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐3块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-20"
    },
    {
      "id": 842506,
      "owner": 2,
      "currency": 14,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐14",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-20"
    }
  ],
  "2016-07-21": [
    {
      "id": 842933,
      "owner": 2,
      "currency": 15,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐十五！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-21"
    },
    {
      "id": 842504,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐三块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-21"
    }
  ],
  "2016-07-22": [
    {
      "id": 843010,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 2,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "地铁4块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-22"
    },
    {
      "id": 843009,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐3块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-22"
    },
    {
      "id": 843011,
      "owner": 2,
      "currency": 0,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "借胖子两千块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-22"
    },
    {
      "id": 844419,
      "owner": 2,
      "currency": 11.8,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "搬家买水118",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-22"
    }
  ],
  "2016-07-23": [
    {
      "id": 844413,
      "owner": 2,
      "currency": 55,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "跟胖子吃饭55元，胖子付的",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-23"
    },
    {
      "id": 844422,
      "owner": 2,
      "currency": 28,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐28",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-23"
    }
  ],
  "2016-07-24": [
    {
      "id": 844414,
      "owner": 2,
      "currency": 151,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "跟丫头吃龙虾151",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-24"
    },
    {
      "id": 844421,
      "owner": 2,
      "currency": 6,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐6元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-24"
    }
  ],
  "2016-07-25": [
    {
      "id": 844420,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐4元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-25"
    }
  ],
  "2016-07-26": [
    {
      "id": 846080,
      "owner": 2,
      "currency": 14,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "我才十四。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-26"
    },
    {
      "id": 846076,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐四块。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-26"
    }
  ],
  "2016-07-27": [
    {
      "id": 846082,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐四块。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-27"
    },
    {
      "id": 846075,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐四块。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-27"
    },
    {
      "id": 846079,
      "owner": 2,
      "currency": 15,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐十五。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-27"
    }
  ],
  "2016-07-28": [
    {
      "id": 846099,
      "owner": 2,
      "currency": 77,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "遮光布77",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-28"
    },
    {
      "id": 846098,
      "owner": 2,
      "currency": 63,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "淘宝63",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-28"
    },
    {
      "id": 846084,
      "owner": 2,
      "currency": 100,
      "currency_type": 1,
      "type": 0,
      "category": 3,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买厨具一百。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-28"
    },
    {
      "id": 846078,
      "owner": 2,
      "currency": 30,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "购买百度外卖会员三十块。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-28"
    },
    {
      "id": 846077,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐四块。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-28"
    },
    {
      "id": 846073,
      "owner": 2,
      "currency": 10.9,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐十块九毛。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-28"
    },
    {
      "id": 846083,
      "owner": 2,
      "currency": 10,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买奶十块。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-28"
    }
  ],
  "2016-07-29": [
    {
      "id": 846236,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐4元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-29"
    },
    {
      "id": 846602,
      "owner": 2,
      "currency": 17,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐17",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-29"
    },
    {
      "id": 847077,
      "owner": 2,
      "currency": 18,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐18",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-29"
    }
  ],
  "2016-07-30": [
    {
      "id": 847078,
      "owner": 2,
      "currency": 101.8,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "家乐福1018",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-30"
    },
    {
      "id": 847079,
      "owner": 2,
      "currency": 127,
      "currency_type": 1,
      "type": 0,
      "category": 3,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "校外酒家127",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-30"
    }
  ],
  "2016-07-31": [
    {
      "id": 847080,
      "owner": 2,
      "currency": 0.82,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "葱，八角18",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-07-31"
    }
  ],
  "2016-08-01": [
    {
      "id": 848051,
      "owner": 2,
      "currency": 7,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐七元。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-01"
    },
    {
      "id": 848052,
      "owner": 2,
      "currency": 16,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐十六。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-01"
    }
  ],
  "2016-08-02": [
    {
      "id": 848118,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐4元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-02"
    }
  ],
  "2016-08-03": [
    {
      "id": 849108,
      "owner": 2,
      "currency": 13.8,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐十三块八。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-03"
    },
    {
      "id": 849109,
      "owner": 2,
      "currency": 70,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "城隍庙小吃七十块钱。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-03"
    },
    {
      "id": 849110,
      "owner": 2,
      "currency": 50,
      "currency_type": 1,
      "type": 0,
      "category": 6,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "给自己充话费五十。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-03"
    },
    {
      "id": 849111,
      "owner": 2,
      "currency": 30,
      "currency_type": 1,
      "type": 0,
      "category": 6,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "给丫头充话费三十。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-03"
    }
  ],
  "2016-08-04": [
    {
      "id": 849107,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐四元。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-04"
    },
    {
      "id": 852320,
      "owner": 2,
      "currency": 12,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐12",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-04"
    },
    {
      "id": 852333,
      "owner": 2,
      "currency": 26.7,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "全家买梅子酸奶瓜子二十六块七毛。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-04"
    }
  ],
  "2016-08-05": [
    {
      "id": 852310,
      "owner": 2,
      "currency": 9,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐9块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-05"
    },
    {
      "id": 852314,
      "owner": 2,
      "currency": 122,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐校外酒家122",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-05"
    },
    {
      "id": 852315,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐3元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-05"
    },
    {
      "id": 852316,
      "owner": 2,
      "currency": 30,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "充交通卡30",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-05"
    },
    {
      "id": 852318,
      "owner": 2,
      "currency": 0,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "田林的房子退了，房东扣了400块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-05"
    },
    {
      "id": 852319,
      "owner": 2,
      "currency": 246.5,
      "currency_type": 1,
      "type": 0,
      "category": 2,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "给丫头买火车票2465",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-05"
    }
  ],
  "2016-08-06": [
    {
      "id": 852305,
      "owner": 2,
      "currency": 0,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚上逛了新天地0元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-06"
    },
    {
      "id": 852306,
      "owner": 2,
      "currency": 0,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐丫头请客吃了大村小馆0元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-06"
    }
  ],
  "2016-08-07": [
    {
      "id": 852298,
      "owner": 2,
      "currency": 12,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "全家买梅子12",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-07"
    },
    {
      "id": 852300,
      "owner": 2,
      "currency": 15,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "从同济逛操场回来的路上买水果15",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-07"
    },
    {
      "id": 852302,
      "owner": 2,
      "currency": 54,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐校外酒家54",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-07"
    },
    {
      "id": 852303,
      "owner": 2,
      "currency": 13.8,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "天猫购买暖宝宝138",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-07"
    }
  ],
  "2016-08-08": [
    {
      "id": 852292,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐4块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-08"
    },
    {
      "id": 852293,
      "owner": 2,
      "currency": 6.9,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐69",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-08"
    },
    {
      "id": 852294,
      "owner": 2,
      "currency": 15,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐买菜15",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-08"
    },
    {
      "id": 852295,
      "owner": 2,
      "currency": 0,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "张丁还了500块钱",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-08"
    }
  ],
  "2016-08-09": [
    {
      "id": 852287,
      "owner": 2,
      "currency": 0,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "今天七夕节0元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-09"
    },
    {
      "id": 852288,
      "owner": 2,
      "currency": 122,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "家乐福购物122",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-09"
    },
    {
      "id": 852289,
      "owner": 2,
      "currency": 23,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午饭23",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-09"
    },
    {
      "id": 852290,
      "owner": 2,
      "currency": 42,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买七夕节礼物寿司42",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-09"
    },
    {
      "id": 852291,
      "owner": 2,
      "currency": 8.3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐83，吃了酸奶和鸡腿包",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-09"
    }
  ],
  "2016-08-10": [
    {
      "id": 852283,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐4块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-10"
    },
    {
      "id": 852284,
      "owner": 2,
      "currency": 50,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐请鹏伟50",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-10"
    },
    {
      "id": 852285,
      "owner": 2,
      "currency": 20,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买交通卡20元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-10"
    },
    {
      "id": 852286,
      "owner": 2,
      "currency": 30,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "充交通卡30",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-10"
    }
  ],
  "2016-08-11": [
    {
      "id": 852618,
      "owner": 2,
      "currency": 13.5,
      "currency_type": 1,
      "type": 0,
      "category": 6,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "小米电话包话费充值135",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-11"
    },
    {
      "id": 852594,
      "owner": 2,
      "currency": 14,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐14",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-11"
    }
  ],
  "2016-08-12": [
    {
      "id": 853517,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐四块。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-12"
    },
    {
      "id": 853518,
      "owner": 2,
      "currency": 14,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐十四。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-12"
    },
    {
      "id": 853519,
      "owner": 2,
      "currency": 25,
      "currency_type": 1,
      "type": 0,
      "category": 2,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "打车二十五。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-12"
    }
  ],
  "2016-08-13": [
    {
      "id": 853641,
      "owner": 2,
      "currency": 17,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买酸奶十七。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-13"
    },
    {
      "id": 853520,
      "owner": 2,
      "currency": 15.5,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐十五块五。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-13"
    }
  ],
  "2016-08-14": [
    {
      "id": 854183,
      "owner": 2,
      "currency": 18,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐18",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-14"
    },
    {
      "id": 854185,
      "owner": 2,
      "currency": 23,
      "currency_type": 1,
      "type": 0,
      "category": 3,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "小米充电器23",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-14"
    }
  ],
  "2016-08-15": [
    {
      "id": 854288,
      "owner": 2,
      "currency": 13,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐13元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-15"
    },
    {
      "id": 854184,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐4块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-15"
    }
  ],
  "2016-08-16": [
    {
      "id": 854693,
      "owner": 2,
      "currency": 25,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐25元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-16"
    },
    {
      "id": 854692,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐4元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-16"
    }
  ],
  "2016-08-17": [
    {
      "id": 855346,
      "owner": 2,
      "currency": 118,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐，五个人，我付的钱一百一十八。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-17"
    },
    {
      "id": 855344,
      "owner": 2,
      "currency": 100,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "充交通卡一百。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-17"
    },
    {
      "id": 855222,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 2,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "地铁4元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-17"
    },
    {
      "id": 855221,
      "owner": 2,
      "currency": 10,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐10元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-17"
    },
    {
      "id": 855220,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐4元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-17"
    }
  ],
  "2016-08-18": [
    {
      "id": 855651,
      "owner": 2,
      "currency": 9,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐9元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-18"
    },
    {
      "id": 855650,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐4元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-18"
    },
    {
      "id": 855486,
      "owner": 2,
      "currency": 13.5,
      "currency_type": 1,
      "type": 0,
      "category": 6,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "小米话费加油包充值135",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-18"
    }
  ],
  "2016-08-19": [
    {
      "id": 856739,
      "owner": 2,
      "currency": 8.9,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐89",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-19"
    },
    {
      "id": 856740,
      "owner": 2,
      "currency": 18.9,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐189",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-19"
    },
    {
      "id": 856741,
      "owner": 2,
      "currency": 15,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐15",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-19"
    }
  ],
  "2016-08-20": [
    {
      "id": 856744,
      "owner": 2,
      "currency": 32,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "周六一天餐饮32",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-20"
    },
    {
      "id": 856745,
      "owner": 2,
      "currency": 2.5,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "馒头25",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-20"
    }
  ],
  "2016-08-21": [
    {
      "id": 856747,
      "owner": 2,
      "currency": 17.88,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "周日一天餐饮1788",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-21"
    }
  ],
  "2016-08-22": [
    {
      "id": 857400,
      "owner": 2,
      "currency": 59.3,
      "currency_type": 1,
      "type": 0,
      "category": 3,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买书593",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-22"
    },
    {
      "id": 857399,
      "owner": 2,
      "currency": 13.8,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐138",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-22"
    },
    {
      "id": 857398,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐4元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-22"
    }
  ],
  "2016-08-23": [
    {
      "id": 858155,
      "owner": 2,
      "currency": 193,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "淘宝购物零食193",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-23"
    },
    {
      "id": 857811,
      "owner": 2,
      "currency": 101,
      "currency_type": 1,
      "type": 0,
      "category": 0,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "淘宝购物101",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-23"
    }
  ],
  "2016-08-24": [
    {
      "id": 860410,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐4元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-24"
    },
    {
      "id": 860411,
      "owner": 2,
      "currency": 40,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐40",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-24"
    }
  ],
  "2016-08-25": [
    {
      "id": 860407,
      "owner": 2,
      "currency": 11,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐11",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-25"
    },
    {
      "id": 860408,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐3元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-25"
    }
  ],
  "2016-08-26": [
    {
      "id": 860406,
      "owner": 2,
      "currency": 13,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐13",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-26"
    },
    {
      "id": 860409,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐3元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-26"
    }
  ],
  "2016-08-27": [
    {
      "id": 860405,
      "owner": 2,
      "currency": 19,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "一天餐饮19",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-27"
    },
    {
      "id": 860413,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "馒头4块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-27"
    }
  ],
  "2016-08-28": [
    {
      "id": 860404,
      "owner": 2,
      "currency": 23.4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "一天餐饮234",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-28"
    }
  ],
  "2016-08-29": [
    {
      "id": 860857,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐4元",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-29"
    },
    {
      "id": 860858,
      "owner": 2,
      "currency": 11.8,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐118",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-29"
    },
    {
      "id": 860859,
      "owner": 2,
      "currency": 14,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐14",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-29"
    }
  ],
  "2016-08-30": [
    {
      "id": 861124,
      "owner": 2,
      "currency": 50,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚上跟同事吃饭，两个人50块，我付钱",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-30"
    },
    {
      "id": 860952,
      "owner": 2,
      "currency": 15,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐15",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-30"
    },
    {
      "id": 860846,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐3块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-30"
    }
  ],
  "2016-08-31": [
    {
      "id": 861705,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐3块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-31"
    },
    {
      "id": 861706,
      "owner": 2,
      "currency": 14,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐14",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-31"
    },
    {
      "id": 861707,
      "owner": 2,
      "currency": 12,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐12",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-08-31"
    }
  ],
  "2016-09-01": [
    {
      "id": 863595,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐四块。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-09-01"
    },
    {
      "id": 863596,
      "owner": 2,
      "currency": 11,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐十一。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-09-01"
    },
    {
      "id": 861831,
      "owner": 2,
      "currency": 16,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐16",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-09-01"
    }
  ],
  "2016-09-02": [
    {
      "id": 862458,
      "owner": 2,
      "currency": 3,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "早餐3块",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-09-02"
    },
    {
      "id": 863591,
      "owner": 2,
      "currency": 13,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "晚餐十三。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-09-02"
    },
    {
      "id": 863592,
      "owner": 2,
      "currency": 40,
      "currency_type": 1,
      "type": 0,
      "category": 6,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "充话费四十。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-09-02"
    },
    {
      "id": 863597,
      "owner": 2,
      "currency": 8,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "午餐八块吧！",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-09-02"
    }
  ],
  "2016-09-04": [
    {
      "id": 863594,
      "owner": 2,
      "currency": 4,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "买馒头四块。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-09-04"
    },
    {
      "id": 863593,
      "owner": 2,
      "currency": 23,
      "currency_type": 1,
      "type": 0,
      "category": 1,
      "reimburse": 0,
      "audio": "",
      "photo": "",
      "location": "",
      "memo": "周末餐饮二十三。",
      "user_id": 47551,
      "weixin_id": "",
      "datetime": "2016-09-04"
    }
  ]
};
//在微信登录的情况下打开多多记账之后可以看到页面已经发送的请求里有一个
//auth_token，把它记录下来，替换下面
var auth_token = "eyJ1aWQiOjE3ODIzNiwidWtleSI6IjA0ZDJjZTk1OWQxYmRkMDcwYjI2ODdlMDkxOWE4NmI5In0=";
/*******end*******/

//js暂停函数
function sleep(numberMillis) { 
	var now = new Date(); 
	var exitTime = now.getTime() + numberMillis; 
	while (true) { 
		now = new Date(); 
		if (now.getTime() > exitTime) 
			return; 
	} 
}

//导入用函数
function importBill(auth_token,datetime,money,remark,categoryId){
	console.log('导入条目 ' + datetime + ' ' + remark);
	window.xhttp.open("POST","http://duo.qq.com/api/addBill",true);
	window.xhttp.setRequestHeader("Content-type","application/x-www-form-urlencoded;charset=UTF-8");
	window.xhttp.setRequestHeader("Accept","application/json, text/plain, */*");
	window.xhttp.setRequestHeader("Auth-Token",auth_token);
	window.xhttp.send("categoryId=" + categoryId + "&recordTime="+datetime+"&money="+ money +"&remark=" + remark);
}

var xhttp = new XMLHttpRequest;

var day_data;
var one_bill;

for(day in data){
	day_data=data[day];
	for(bill in day_data){
		one_bill = day_data[bill];
		importBill(auth_token,one_bill.datetime,one_bill.currency,one_bill.memo,203);
		sleep(1000);
	}
}